Traceback (most recent call last):
  File "c:\users\notes\anaconda3\envs\book\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\notes\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\notes\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\notes\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\notes\anaconda3\envs\book\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\notes\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "c:\users\notes\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\notes\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import pandas as pd

r = np.array([3,3,3,4,2,2,2,1])  # amount each of the 7 people can eat
c = np.array([4,2,6,4,4])  # portions of the 5 desserts available
M = np.array([[2,2,1,0,0],
              [0,-2,-2,-2,2],
              [1,2,2,2,-1],
              [2,1,0,1,-1],
              [0.5,2,2,1,0],
              [0,1,1,1,-1],
              [-2,2,2,1,1],
              [2,1,2,1,-1]])  # (n x m) preferences matrix
M = -M  # converting preferences to cost
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-1-baa1a268ac62>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [1;32mimport[0m [0mpandas[0m [1;32mas[0m [0mpd[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [1;33m[0m[0m
[0;32m      4[0m [0mr[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0marray[0m[1;33m([0m[1;33m[[0m[1;36m3[0m[1;33m,[0m[1;36m3[0m[1;33m,[0m[1;36m3[0m[1;33m,[0m[1;36m4[0m[1;33m,[0m[1;36m2[0m[1;33m,[0m[1;36m2[0m[1;33m,[0m[1;36m2[0m[1;33m,[0m[1;36m1[0m[1;33m][0m[1;33m)[0m  [1;31m# amount each of the 7 people can eat[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mc[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0marray[0m[1;33m([0m[1;33m[[0m[1;36m4[0m[1;33m,[0m[1;36m2[0m[1;33m,[0m[1;36m6[0m[1;33m,[0m[1;36m4[0m[1;33m,[0m[1;36m4[0m[1;33m][0m[1;33m)[0m  [1;31m# portions of the 5 desserts available[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

